=== Rita-Rosendo/PRI2020/TP3/arq.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ARQSITS (ARQELEM)+ >
<!ELEMENT ARQELEM (TIPO,IDENTI,IMAGEM?, DESCRI, CRONO?, LUGAR, FREGUE, CONCEL, CODADM, LATITU, ALTITU, ACESSO, QUADRO, TRAARQ?, DESARQ, INTERP, INTERE?, DEPOSI, BIBLIO*, AUTOR, DATA) >

<!ELEMENT TIPO (#PCDATA) >
<!ATTLIST TIPO
    ASSUNTO CDATA #REQUIRED >

<!ELEMENT IDENTI (#PCDATA) >

<!ELEMENT IMAGEM (#PCDATA) >
<!ATTLIST IMAGEM
    NOME CDATA #REQUIRED >
    
<!ELEMENT DESCRI (LIGA)>
<!ELEMENT LIGA (#PCDATA) >
<!ATTLIST LIGA
    TERMO CDATA #REQUIRED >
<!ELEMENT CRONO (#PCDATA) >
<!ELEMENT LUGAR (#PCDATA) >
<!ELEMENT FREGUE (#PCDATA) >
<!ELEMENT CONCEL (#PCDATA) >
<!ELEMENT CODADM (#PCDATA) >
<!ELEMENT LATITU (#PCDATA) >
<!ELEMENT ALTITU (#PCDATA) >
<!ELEMENT ACESSO (#PCDATA) >
<!ELEMENT QUADRO (#PCDATA|LIGA)* >
<!ELEMENT TRAARQ (#PCDATA) >
<!ELEMENT DESARQ (#PCDATA|LIGA)* >
<!ELEMENT INTERP (#PCDATA|LIGA)* >
<!ELEMENT INTERE (#PCDATA) >
<!ELEMENT DEPOSI (#PCDATA) >
<!ELEMENT BIBLIO (#PCDATA) >
<!ELEMENT AUTOR (#PCDATA) >
<!ELEMENT DATA (#PCDATA) >

=== Rita-Rosendo/PRI2020/TP3/arqFromdtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ARQSITS SYSTEM "file:/home/aninhas/Desktop/2020_2021/PLC/PRI/TPC/TP3/arq.dtd">
<ARQSITS>
    <ARQELEM>
        <TIPO ASSUNTO=""></TIPO>
        <IDENTI></IDENTI>
        <DESCRI>
            <LIGA TERMO=""></LIGA>
        </DESCRI>
        <LUGAR></LUGAR>
        <FREGUE></FREGUE>
        <CONCEL></CONCEL>
        <CODADM></CODADM>
        <LATITU></LATITU>
        <ALTITU></ALTITU>
        <ACESSO></ACESSO>
        <QUADRO></QUADRO>
        <DESARQ></DESARQ>
        <INTERP></INTERP>
        <DEPOSI></DEPOSI>
        <AUTOR></AUTOR>
        <DATA></DATA>
    </ARQELEM>
</ARQSITS>
